### ISSUE TITLE
VPN config - PfSense

### ISSUE THREAD

**Issue by deffus** [cydea/remote-working-psirt#1]
would add pfsense config for VPN option , something like https://docs.netgate.com/pfsense/en/latest/vpn/openvpn/openvpn-remote-access-server.html in case some org are running open source tooling

**Comment by rto** [comment]
Great idea and thanks for the link.

In this case I think it's worthwhile treating Netgate as the 'vendor' and so linking to them is OK. (Trying to keep to vendor-only docs for their solutions.)
